### PR TITLE
Create new test

### PR DESCRIPTION
**Pull request by rprimet**

### CODE REVIEW

**Comment by rprimet** [comment]
This is not yet robust and needs a few workarounds, but we could consider merging it and moving to the actual/expected results comparison in view of the CNAF demo?

Recording 2024-10-10 at 11 02 48

**Comment by denismerigoux** [comment]
This looks very nice! I have one suggestion though: in my opinion, all the tests in a test file should test maybe not the same scope, but at least scopes of the same Catala file (included or used as a dependent module). So for me, the `filename` input to the "new test" form should not be repeated for each new test in the file. Instead, it should be assumed new tests in a file already containing tests while test scopes of the same file as the tests already present. Does it make sense?

**Comment by rprimet** [comment]
It does make sense, but the thing I had in mind would be to actually just pick symbols / scopes and let the project (clerk...) figure out the file ; so that's kind of a dummy workaround (also the fact that we need to put the filename relative to the cwd, this is totally clunky and won't work for real users). So yes! I can try to at least wire completion for the filenames, but I think we can have a UI that is nice to use without having to restraining users to testing scopes in a single module. What do you think? I'll let you decide!

**Comment by denismerigoux** [comment]
OK, let's go for no restrictions for the users and let future selves implement the clever completions later :)

**Comment by rprimet** [comment]
thanks!

**Pull request merged**
